language: java

notifications:
  email: false

script: "mvn cobertura:cobertura"

services:
- postgresql

before_script:
- psql -c "CREATE database songs_db;
           CREATE role prorgam WITH password 'test';
           GRANT ALL PRIVELEGES ON database songs_db TO program;
           ALTER role program WITH login;" -U postgres

after_success:
- bash <(curl -s https://codecov.io/bash)

