language: java

notifications:
  email: false

script: "mvn cobertura:cobertura"

services:
- postgresql

before_script:
- psql -c "create database songs_db;" -U postgres
- psql -c "create role prorgam WITH password 'test';" -U postgres
- psql -c "GRANT ALL PRIVILEGES ON database songs_db TO program;" -U postgres
- psql -c "ALTER role program WITH login;" -U postgres

after_success:
- bash <(curl -s https://codecov.io/bash)

